# Generated by Django 4.2.7 on 2026-02-25 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('light', 'Light'), ('fan', 'Fan'), ('door', 'Door'), ('lock', 'Smart Lock'), ('ac', 'Air Conditioner'), ('tv', 'Television'), ('speaker', 'Smart Speaker'), ('curtain', 'Curtain'), ('pump', 'Water Pump'), ('other', 'Other')], max_length=20)),
                ('room', models.CharField(blank=True, help_text='Room where device is located', max_length=100)),
                ('pin_number', models.IntegerField(blank=True, help_text='Arduino/GPIO pin number', null=True)),
                ('arduino_id', models.CharField(blank=True, help_text='Arduino board identifier', max_length=50)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Under Maintenance'), ('error', 'Error')], default='offline', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('current_state', models.CharField(default='off', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('supports_dimming', models.BooleanField(default=False)),
                ('supports_color', models.BooleanField(default=False)),
                ('supports_speed', models.BooleanField(default=False)),
                ('supports_temperature', models.BooleanField(default=False)),
                ('min_value', models.IntegerField(default=0)),
                ('max_value', models.IntegerField(default=100)),
                ('current_value', models.IntegerField(default=0, help_text='Current value (brightness/speed/etc)')),
                ('power_rating', models.FloatField(blank=True, help_text='Power rating in watts', null=True)),
                ('energy_today', models.FloatField(default=0, help_text='Energy used today in kWh')),
                ('energy_total', models.FloatField(default=0, help_text='Total energy used in kWh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.CharField(default='default-device', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'devices',
                'ordering': ['room', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('days', models.JSONField(default=list, help_text='List of weekday numbers (0-6)')),
                ('action', models.CharField(max_length=20)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
            options={
                'db_table': 'schedules',
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='scene', max_length=50)),
                ('device_states', models.JSONField(default=dict, help_text='Dictionary of device_id: state')),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule_time', models.TimeField(blank=True, null=True)),
                ('schedule_days', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scenes',
            },
        ),
        migrations.CreateModel(
            name='EnergyMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.FloatField(help_text='Current power in watts')),
                ('voltage', models.FloatField(blank=True, null=True)),
                ('current', models.FloatField(blank=True, null=True)),
                ('energy', models.FloatField(help_text='Energy in kWh')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_readings', to='devices.device')),
            ],
            options={
                'db_table': 'energy_monitoring',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room', models.CharField(blank=True, max_length=100)),
                ('devices', models.ManyToManyField(related_name='groups', to='devices.device')),
            ],
            options={
                'db_table': 'device_groups',
            },
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules execute first')),
                ('condition_type', models.CharField(choices=[('time', 'Time Based'), ('temperature', 'Temperature'), ('humidity', 'Humidity'), ('light', 'Light Level'), ('motion', 'Motion Detected'), ('door', 'Door Status'), ('schedule', 'Schedule'), ('manual', 'Manual Trigger')], max_length=20)),
                ('operator', models.CharField(blank=True, choices=[('gt', 'Greater Than (>)'), ('lt', 'Less Than (<)'), ('eq', 'Equal To (=)'), ('gte', 'Greater Than or Equal (≥)'), ('lte', 'Less Than or Equal (≤)'), ('ne', 'Not Equal (≠)'), ('between', 'Between')], max_length=10)),
                ('threshold_value', models.FloatField(blank=True, null=True)),
                ('threshold_max', models.FloatField(blank=True, null=True)),
                ('specific_time', models.TimeField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('days_of_week', models.JSONField(blank=True, default=list)),
                ('action_type', models.CharField(choices=[('device_on', 'Turn Device On'), ('device_off', 'Turn Device Off'), ('device_toggle', 'Toggle Device'), ('device_lock', 'Lock Device'), ('device_unlock', 'Unlock Device'), ('device_open', 'Open Device'), ('device_close', 'Close Device'), ('device_value', 'Set Device Value'), ('notification', 'Send Notification'), ('webhook', 'Call Webhook'), ('scene', 'Activate Scene')], max_length=20)),
                ('action_value', models.CharField(blank=True, help_text='Value to set (for device_value action)', max_length=100)),
                ('additional_actions', models.JSONField(blank=True, default=list)),
                ('cooldown_minutes', models.IntegerField(default=0)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('trigger_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensors.sensor')),
                ('target_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='devices.device')),
            ],
            options={
                'db_table': 'automation_rules',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='devices.device')),
            ],
            options={
                'db_table': 'device_status',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', '-timestamp'], name='device_stat_device__a5d34b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_type'], name='devices_device__f7aa79_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['room'], name='devices_room_eb941b_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status'], name='devices_status_9f14cf_idx'),
        ),
    ]
