# Generated by Django 4.2.7 on 2026-02-25 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sensor_type', models.CharField(choices=[('temperature', 'Temperature Sensor'), ('humidity', 'Humidity Sensor'), ('light', 'Light Sensor (LDR)'), ('ultrasonic', 'Ultrasonic Sensor'), ('motion', 'Motion Sensor'), ('gas', 'Gas Sensor'), ('smoke', 'Smoke Sensor')], max_length=20)),
                ('location', models.CharField(help_text='Where is the sensor installed?', max_length=100)),
                ('pin_number', models.IntegerField(blank=True, help_text='Arduino pin number', null=True)),
                ('unit', models.CharField(blank=True, help_text='Measurement unit (e.g., °C, %, cm)', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance'), ('error', 'Error')], default='inactive', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('calibration_value', models.FloatField(default=0.0, help_text='Calibration offset')),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('last_reading', models.FloatField(blank=True, null=True)),
                ('last_read_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sensors',
                'ordering': ['sensor_type', 'location'],
            },
        ),
        migrations.CreateModel(
            name='SensorThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('condition_type', models.CharField(choices=[('gt', 'Greater Than'), ('lt', 'Less Than'), ('eq', 'Equal To'), ('between', 'Between')], max_length=10)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('action_type', models.CharField(choices=[('alert', 'Send Alert'), ('email', 'Send Email'), ('sms', 'Send SMS'), ('webhook', 'Call Webhook'), ('device_action', 'Control Device')], max_length=20)),
                ('action_config', models.JSONField(default=dict, help_text='Configuration for the action')),
                ('is_time_restricted', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cooldown_minutes', models.IntegerField(default=5, help_text='Minutes between alerts')),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='sensors.sensor')),
            ],
            options={
                'db_table': 'sensor_thresholds',
            },
        ),
        migrations.CreateModel(
            name='SensorCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_offset', models.FloatField()),
                ('new_offset', models.FloatField()),
                ('calibration_point', models.FloatField(help_text='Reference value used for calibration')),
                ('measured_value', models.FloatField(help_text='Actual measured value')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calibrated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='sensors.sensor')),
            ],
            options={
                'db_table': 'sensor_calibrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('threshold_exceeded', 'Threshold Exceeded'), ('threshold_below', 'Threshold Below'), ('sensor_error', 'Sensor Error'), ('sensor_offline', 'Sensor Offline'), ('battery_low', 'Battery Low')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('message', models.TextField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='sensors.sensor')),
            ],
            options={
                'db_table': 'sensor_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('period_type', models.CharField(choices=[('hour', 'Hourly'), ('day', 'Daily'), ('week', 'Weekly'), ('month', 'Monthly')], max_length=10)),
                ('avg_value', models.FloatField(blank=True, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('median_value', models.FloatField(blank=True, null=True)),
                ('std_deviation', models.FloatField(blank=True, null=True)),
                ('reading_count', models.IntegerField(default=0)),
                ('alert_count', models.IntegerField(default=0)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='sensors.sensor')),
            ],
            options={
                'db_table': 'sensor_statistics',
                'unique_together': {('sensor', 'period_start', 'period_type')},
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('light_level', models.IntegerField(blank=True, help_text='LDR value (0-1023)', null=True)),
                ('distance', models.FloatField(blank=True, help_text='Distance in cm', null=True)),
                ('motion_detected', models.BooleanField(default=False)),
                ('raw_value', models.FloatField(blank=True, null=True)),
                ('calibrated_value', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('battery_level', models.FloatField(blank=True, null=True)),
                ('signal_strength', models.IntegerField(blank=True, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensor')),
            ],
            options={
                'db_table': 'sensor_data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor', '-timestamp'], name='sensor_data_sensor__d6a7cf_idx'), models.Index(fields=['timestamp'], name='sensor_data_timesta_97a1d1_idx')],
            },
        ),
    ]
