# Generated by Django 4.2.7 on 2026-04-04 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(help_text='Where is the camera installed?', max_length=100)),
                ('camera_id', models.IntegerField(default=0, help_text='Camera device ID (0 for default)')),
                ('resolution', models.CharField(choices=[('640x480', '640x480'), ('1280x720', '1280x720 (HD)'), ('1920x1080', '1920x1080 (Full HD)')], default='640x480', max_length=20)),
                ('fps', models.IntegerField(default=30, help_text='Frames per second')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.IntegerField(default=8080)),
                ('rtsp_url', models.URLField(blank=True, help_text='RTSP URL for IP cameras')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('recording', 'Recording'), ('error', 'Error')], default='offline', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_recording', models.BooleanField(default=False)),
                ('recording_quality', models.IntegerField(default=80, help_text='Recording quality (1-100)')),
                ('motion_detection', models.BooleanField(default=False)),
                ('has_audio', models.BooleanField(default=False)),
                ('has_ptz', models.BooleanField(default=False, help_text='Pan-Tilt-Zoom support')),
                ('ptz_pan', models.IntegerField(default=0)),
                ('ptz_tilt', models.IntegerField(default=0)),
                ('ptz_zoom', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cameras',
                'ordering': ['location', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MotionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='motion_snapshots/')),
                ('motion_level', models.IntegerField(help_text='Motion intensity (0-100)')),
                ('motion_area', models.TextField(blank=True, help_text='JSON of motion area coordinates')),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motion_events', to='camera.camera')),
            ],
            options={
                'db_table': 'motion_events',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='CameraSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='camera_snapshots/')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='camera.camera')),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'camera_snapshots',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='CameraRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('triggered_by', models.CharField(choices=[('manual', 'Manual'), ('motion', 'Motion Detection'), ('schedule', 'Schedule'), ('alert', 'Security Alert')], default='manual', max_length=50)),
                ('has_motion', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='camera_thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='camera.camera')),
            ],
            options={
                'db_table': 'camera_recordings',
                'ordering': ['-start_time'],
            },
        ),
    ]
